;; docs.clj — docstrings for the core vocabulary, bulk-loaded on the first
;; (doc ...) / (find-doc ...) via cljc/ensure-docs!. Entries are keyed by the
;; flat root-binding name (bare for core, "str/x" for clojure.string).
;; Texts are condensed from the official Clojure docstrings.

(run! (fn [[n d]] (cljc/doc-put* n d))
 [;; ── sequences ──
  ["map" "Returns a lazy sequence of applying f to each item of coll (or to the items of multiple colls in parallel, stopping at the shortest). (map f) returns a transducer."]
  ["filter" "Returns a lazy sequence of the items in coll for which (pred item) is logical true. (filter pred) returns a transducer."]
  ["remove" "Returns a lazy sequence of the items for which (pred item) is logical false."]
  ["reduce" "(reduce f coll) or (reduce f init coll): applies f to an accumulator and each item, left to right. With no init, first two items seed the call; empty coll => (f)."]
  ["reductions" "Returns a lazy seq of the intermediate values of a reduction, starting with init (or the first item)."]
  ["reduce-kv" "Reduces an associative collection: (f acc key val) for every entry. Vectors use their indices as keys."]
  ["mapcat" "Applies f to every item and concatenates the (collection) results, lazily."]
  ["mapv" "Like map but eager, returning a vector."]
  ["filterv" "Like filter but eager, returning a vector."]
  ["keep" "Lazy sequence of the non-nil results of (f item)."]
  ["keep-indexed" "Lazy sequence of the non-nil results of (f index item)."]
  ["map-indexed" "Lazy sequence of (f index item) for each item."]
  ["take" "Lazy sequence of the first n items. (take n) is a transducer."]
  ["drop" "Lazy sequence of all but the first n items."]
  ["take-while" "Lazy items from the front while (pred item) is true."]
  ["drop-while" "Lazy items after the leading run where (pred item) is true."]
  ["take-nth" "Every nth item of coll, lazily."]
  ["take-last" "The last n items of coll (eager)."]
  ["drop-last" "All but the last n items, lazily."]
  ["first" "The first item of coll, or nil when empty."]
  ["second" "Same as (first (next coll))."]
  ["rest" "The items after the first; () when none. Never nil."]
  ["next" "The items after the first, or nil when none remain."]
  ["last" "The final item of coll (walks the whole seq)."]
  ["butlast" "Everything but the final item (eager)."]
  ["nth" "The item at index n. Throws when out of bounds unless a not-found is given."]
  ["cons" "A seq whose first is x and whose rest is coll."]
  ["conj" "Adds item(s) to a collection at its natural insertion point: vectors append, lists prepend, sets/maps add."]
  ["concat" "Lazy concatenation of any number of collections."]
  ["into" "Adds every item of `from` onto `to` (conj semantics); (into to xform from) applies a transducer."]
  ["seq" "A seq view of the collection, or nil when it is empty. The idiomatic emptiness test."]
  ["empty?" "True when coll has no items — same as (not (seq coll))."]
  ["count" "The number of items in the collection (O(1) for counted colls)."]
  ["range" "(range), (range end), (range start end step): lazy seq of numbers. No args = infinite."]
  ["repeat" "(repeat x) infinite xs; (repeat n x) n of them. Lazy."]
  ["repeatedly" "Lazy sequence of calls to a zero-arg (side-effecting) fn."]
  ["iterate" "Lazy infinite seq of x, (f x), (f (f x)), ..."]
  ["cycle" "Lazy infinite repetition of the items of coll."]
  ["interleave" "First items of each coll, then second items, etc., stopping at the shortest."]
  ["interpose" "The items of coll separated by sep, lazily."]
  ["partition" "Lazy blocks of n items (optionally stepped/padded); incomplete tail block is dropped unless padded."]
  ["partition-all" "Like partition but keeps the incomplete final block."]
  ["partition-by" "Splits coll each time (f item) changes value, lazily."]
  ["split-at" "[(take n coll) (drop n coll)]"]
  ["split-with" "[(take-while pred coll) (drop-while pred coll)]"]
  ["distinct" "Lazy sequence with duplicates removed."]
  ["dedupe" "Lazy sequence with consecutive duplicates collapsed."]
  ["flatten" "All nested sequential items as one flat lazy sequence."]
  ["reverse" "The items in reverse order (eager)."]
  ["sort" "Sorted seq of coll; (sort comp coll) with a comparator."]
  ["sort-by" "Sorts by (keyfn item), optionally with a comparator."]
  ["shuffle" "A random permutation of coll (note: cljc's is currently identity)."]
  ["frequencies" "Map from distinct item to number of occurrences."]
  ["group-by" "Map from (f item) to vector of items with that key."]
  ["doall" "Forces a lazy sequence completely; returns it. Use for side effects held in a lazy seq."]
  ["dorun" "Forces a lazy sequence for side effects; returns nil."]
  ["lazy-seq" "Wraps body so it is evaluated only when the seq is consumed, once."]
  ["realized?" "Whether a delay/lazy value has been forced (cljc: coarse)."]
  ["some" "The first logical-true value of (pred item), else nil."]
  ["every?" "True if (pred item) is true for every item."]
  ["not-every?" "Complement of every?."]
  ["not-any?" "True when no item satisfies pred."]
  ["zipmap" "A map with keys mapped to vals, stopping at the shorter."]
  ["line-seq" "Lazy seq of lines from a reader."]
  ["tree-seq" "Lazy depth-first walk: branch? decides descent, children expands."]
  ;; ── collections ──
  ["get" "The value at key (or index), or not-found/nil. Works on maps, vectors, sets, strings."]
  ["get-in" "The value at a nested key path, e.g. (get-in m [:a :b])."]
  ["assoc" "Map with key(s) mapped to val(s); on vectors, sets the index (append at count)."]
  ["assoc-in" "Sets a value at a nested key path, creating maps along the way."]
  ["update" "Map with the value at k replaced by (f old & args)."]
  ["update-in" "Like update at a nested key path."]
  ["dissoc" "Map without the given key(s)."]
  ["disj" "Set without the given element(s)."]
  ["merge" "Later maps' entries win: (merge {:a 1} {:a 2 :b 3}) => {:a 2 :b 3}."]
  ["merge-with" "Like merge, resolving key conflicts with (f left right)."]
  ["select-keys" "Map with only the entries whose keys are in keyseq."]
  ["keys" "Sequence of the map's keys."]
  ["vals" "Sequence of the map's values."]
  ["contains?" "Whether the key (or index) is present — NOT a value search; use `some` for that."]
  ["find" "The map entry [k v] for key, or nil."]
  ["peek" "Vectors: last item. Lists/queues: first. Maps (cljc): the min-priority entry."]
  ["pop" "The collection without its peek item."]
  ["subvec" "A vector view of v from start (to end), O(1)."]
  ["vec" "An eager vector of the items of coll."]
  ["vector" "A vector of the arguments."]
  ["set" "A set of the items of coll."]
  ["hash-map" "A map from interleaved key/value arguments."]
  ["hash-set" "A set of the arguments."]
  ["sorted-map" "A map sorted by its keys (compare, or sorted-map-by comparator)."]
  ["sorted-set" "A set sorted by compare (or sorted-set-by comparator)."]
  ["subseq" "Entries of a sorted collection in a key range, e.g. (subseq sm >= 5)."]
  ["rsubseq" "Like subseq, descending."]
  ["transient" "A mutable-in-place edition of a vector/map/set for batch building; finish with persistent!."]
  ["persistent!" "Seals a transient back into an immutable collection."]
  ["conj!" "conj onto a transient."]
  ["assoc!" "assoc onto a transient (or set an int-array slot in cljc)."]
  ["int-array" "(int-array n), (int-array n init), (int-array coll): a flat mutable int64 array (cljc native). Use aget/aset/alength."]
  ["aget" "Reads array slot i, O(1)."]
  ["aset" "Writes array slot i, returning the value."]
  ["alength" "The array's length."]
  ["empty" "An empty collection of the same category as coll."]
  ;; ── functions & control ──
  ["apply" "Calls f with the items of the final argument spliced in as arguments."]
  ["partial" "A fn with some leading arguments preapplied."]
  ["comp" "Right-to-left function composition: ((comp f g) x) is (f (g x))."]
  ["juxt" "((juxt f g) x) => [(f x) (g x)]."]
  ["identity" "Returns its argument."]
  ["constantly" "A fn that ignores its arguments and always returns x."]
  ["fnil" "A fn that substitutes defaults for leading nil arguments before calling f."]
  ["complement" "A fn returning the logical negation of f's result."]
  ["every-pred" "A pred that is true when ALL given preds are true."]
  ["some-fn" "A fn returning the first logical-true result among the given fns."]
  ["memoize" "Caches f's results by argument list."]
  ["trampoline" "Calls f; while the result is a fn, calls it — flat mutual recursion."]
  ["if-let" "Binds then branches: (if-let [x expr] then else) — then runs with x bound when expr is truthy."]
  ["when-let" "(when-let [x expr] body...) — body runs with x bound when expr is truthy."]
  ["if-some" "Like if-let but tests (some? expr), so false is a hit."]
  ["when-some" "Like when-let but tests (some? expr)."]
  ["cond" "Pairs of test/expr: value of the expr after the first truthy test."]
  ["condp" "(condp pred expr & clauses): matches expr against clause keys with pred."]
  ["case" "Constant-time dispatch on identical(ish) constants; throws without a default."]
  ["cond->" "Threads x through the exprs whose paired tests are truthy."]
  ["cond->>" "Like cond-> threading last."]
  ["as->" "Threads through forms binding each result to the given name."]
  ["some->" "Threads while values are non-nil; stops at the first nil."]
  ["some->>" "Like some-> threading last."]
  ["doto" "Evaluates x, threads it as first arg through the forms (for side effects), returns x."]
  ["dotimes" "(dotimes [i n] body): runs body n times with i bound 0..n-1."]
  ["doseq" "Iterates for side effects with for-style bindings (:let/:when/:while); returns nil."]
  ["for" "Lazy list comprehension with :let/:when/:while modifiers."]
  ["loop" "Establishes bindings that recur re-enters with new values."]
  ["recur" "Rebinds the enclosing loop/fn bindings and jumps back — constant-stack iteration."]
  ["while" "Runs body repeatedly while test is truthy."]
  ["run!" "(reduce (fn [_ x] (f x)) nil coll) — eager side effects, returns nil."]
  ;; ── numbers ──
  ["inc" "One greater."]
  ["dec" "One less."]
  ["quot" "Truncating integer division."]
  ["rem" "Remainder with the dividend's sign."]
  ["mod" "Modulus with the divisor's sign (always ≥0 for positive divisors)."]
  ["max" "The greatest argument."]
  ["min" "The least argument."]
  ["abs" "Absolute value."]
  ["gcd" "Greatest common divisor (cljc extension)."]
  ["even?" "Whether n is even."]
  ["odd?" "Whether n is odd."]
  ["zero?" "Whether x is zero."]
  ["pos?" "Whether x is positive."]
  ["neg?" "Whether x is negative."]
  ["parse-long" "The string as a long, or nil if it isn't one."]
  ["parse-double" "The string as a double, or nil."]
  ["rand" "Random double in [0,n) (default n=1)."]
  ["rand-int" "Random integer in [0,n)."]
  ["rand-nth" "A random item of coll."]
  ["compare" "-1/0/1 comparator over comparable values (numbers, strings, keywords, vectors...)."]
  ;; ── strings (flat str/ aliases) ──
  ["str" "Concatenates the string forms of the arguments; nil is \"\"."]
  ["pr-str" "The readable (edn) printed form as a string."]
  ["prn" "Prints readably followed by a newline."]
  ["println" "Prints human-readably with spaces and a newline."]
  ["print" "Prints human-readably without a newline."]
  ["format" "printf-style formatting: %s %d %f %x etc."]
  ["subs" "Substring from start (to end)."]
  ["str/join" "Concatenates the collection's items, optionally separated: (str/join \", \" xs)."]
  ["str/split" "Splits on a regex: (str/split s #\",\" limit?)."]
  ["str/split-lines" "Splits on \\n (and \\r\\n)."]
  ["str/replace" "Replaces all matches of a string or #\"regex\" (with $1.. group refs or a fn)."]
  ["str/replace-first" "Like str/replace, first match only."]
  ["str/trim" "Without leading/trailing whitespace."]
  ["str/triml" "Without leading whitespace."]
  ["str/trimr" "Without trailing whitespace."]
  ["str/upper-case" "ALL CAPS."]
  ["str/lower-case" "all lower."]
  ["str/capitalize" "First char upper, rest lower."]
  ["str/starts-with?" "Whether s begins with substr."]
  ["str/ends-with?" "Whether s ends with substr."]
  ["str/includes?" "Whether s contains substr."]
  ["str/index-of" "First index of a substring/char, or nil."]
  ["str/last-index-of" "Last index of a substring/char, or nil."]
  ["str/blank?" "True for nil, empty, or all-whitespace strings."]
  ["str/reverse" "The string reversed."]
  ;; ── regex ──
  ["re-find" "First match of the pattern in s: the string, or [match groups...] when the pattern has groups."]
  ["re-matches" "Like re-find but the pattern must match the ENTIRE string."]
  ["re-seq" "Lazy sequence of successive matches."]
  ["re-pattern" "Compiles a string into a regex pattern."]
  ["re-replace" "cljc: replace all matches, with $1..$9 group refs in the replacement."]
  ;; ── state ──
  ["atom" "A mutable reference; read with @, update with swap!/reset!."]
  ["swap!" "Sets an atom to (f current args...); returns the new value."]
  ["reset!" "Sets an atom's value directly; returns it."]
  ["swap-vals!" "Like swap! but returns [old new]."]
  ["reset-vals!" "Like reset! but returns [old new]."]
  ["compare-and-set!" "Sets the atom to new only if it currently holds old; returns success."]
  ["deref" "The current value of an atom/delay/promise/var — reader sugar @x."]
  ["delay" "Defers body until the first deref, then caches."]
  ["force" "Derefs a delay, passes other values through."]
  ;; ── predicates & misc ──
  ["nil?" "Whether x is nil."]
  ["some?" "Whether x is NOT nil (false is some?)."]
  ["true?" "Whether x is exactly true."]
  ["false?" "Whether x is exactly false."]
  ["not" "Logical negation."]
  ["boolean" "Coerces to true/false by truthiness."]
  ["string?" "Whether x is a string."]
  ["keyword?" "Whether x is a keyword."]
  ["symbol?" "Whether x is a symbol."]
  ["number?" "Whether x is a number."]
  ["int?" "Whether x is a fixed-precision integer."]
  ["integer?" "Whether x is any integer."]
  ["double?" "Whether x is a double."]
  ["fn?" "Whether x is a function."]
  ["coll?" "Whether x is a collection."]
  ["seq?" "Whether x is a seq (list-like)."]
  ["sequential?" "Whether x is sequential (lists, vectors, seqs)."]
  ["associative?" "Whether x supports key lookup (maps, vectors)."]
  ["vector?" "Whether x is a vector."]
  ["map?" "Whether x is a map."]
  ["set?" "Whether x is a set."]
  ["list?" "Whether x is a list."]
  ["sorted?" "Whether x is a sorted collection."]
  ["keyword" "Makes a keyword from a name (and optional namespace): (keyword \"a\" \"b\") => :a/b."]
  ["symbol" "Makes a symbol from a name (and optional namespace)."]
  ["name" "The name part of a keyword/symbol/string."]
  ["namespace" "The namespace part of a qualified keyword/symbol, or nil."]
  ["gensym" "A unique symbol, optionally with a prefix."]
  ["type" "The value's type (cljc: a keyword like :vector, :string)."]
  ["instance?" "Whether x is of the given type/protocol."]
  ["identical?" "Pointer equality — same object."]
  ["hash" "The value's hash code (consistent with =)."]
  ["meta" "The metadata map of obj, or nil."]
  ["with-meta" "obj with the given metadata map attached."]
  ["vary-meta" "obj with (apply f (meta obj) args) as metadata."]
  ["slurp" "The entire contents of a file/stream as a string."]
  ["spit" "Writes content to a file (stringified)."]
  ["read-string" "Reads one edn/Clojure form from the string."]
  ["eval" "Evaluates a form (data) and returns the result."]
  ["macroexpand-1" "One step of macro expansion for the form."]
  ["macroexpand" "Repeated macroexpand-1 until the head is no longer a macro."]
  ["time" "Evaluates body, prints elapsed time, returns the value."]
  ["assert" "Throws when x is falsy (with optional message)."]
  ["ex-info" "An exception carrying a message and a data map (and optional cause)."]
  ["ex-message" "The message of an exception."]
  ["ex-data" "The data map of an ex-info exception, else nil."]
  ["ex-cause" "The cause of an exception, or nil."]
  ["with-out-str" "Evaluates body capturing everything printed, returning it as a string."]
  ["doc" "Prints documentation for the named binding: (doc map)."]
  ["source" "Prints the (re-read) source of a fn defined from Clojure code: (source my-fn)."]
  ["apropos" "All defined names containing the string: (apropos \"index\")."]
  ["find-doc" "Prints docs for every binding whose name or docstring matches."]
  ;; ── multimethods & protocols ──
  ["defmulti" "Defines a multimethod dispatching on (dispatch-fn args...)."]
  ["defmethod" "Adds a method implementation for a dispatch value."]
  ["defprotocol" "Declares a named set of methods dispatched on the first argument's type."]
  ["defrecord" "Defines a named map-like type with fixed fields and protocol support."]
  ["deftype" "Defines a named type with fields (cljc: represented as a tagged map)."]
  ["derive" "Adds a parent relationship in the (global) hierarchy."]
  ["isa?" "Hierarchy-aware type/tag relation (vectors compare element-wise)."]])
