;; docs.clj — docstrings for the core vocabulary, bulk-loaded on the first
;; (doc ...) / (find-doc ...) via cljc/ensure-docs!. Entries are keyed by the
;; flat root-binding name (bare for core, "str/x" for clojure.string).
;; Texts are condensed from the official Clojure docstrings.

(run! (fn [[n d a]] (cljc/doc-put* n d a))
 [;; ── sequences ──
  ["map" "Returns a lazy sequence of applying f to each item of coll (or to the items of multiple colls in parallel, stopping at the shortest). (map f) returns a transducer." "([f] [f coll] [f c1 c2] [f c1 c2 & colls])"]
  ["filter" "Returns a lazy sequence of the items in coll for which (pred item) is logical true. (filter pred) returns a transducer." "([pred] [pred coll])"]
  ["remove" "Returns a lazy sequence of the items for which (pred item) is logical false." "([pred] [pred coll])"]
  ["reduce" "(reduce f coll) or (reduce f init coll): applies f to an accumulator and each item, left to right. With no init, first two items seed the call; empty coll => (f)." "([f coll] [f init coll])"]
  ["reductions" "Returns a lazy seq of the intermediate values of a reduction, starting with init (or the first item)." "([f coll] [f init coll])"]
  ["reduce-kv" "Reduces an associative collection: (f acc key val) for every entry. Vectors use their indices as keys." "([f init coll])"]
  ["mapcat" "Applies f to every item and concatenates the (collection) results, lazily." "([f] [f & colls])"]
  ["mapv" "Like map but eager, returning a vector." "([f coll] [f c1 c2] [f c1 c2 & colls])"]
  ["filterv" "Like filter but eager, returning a vector." "([pred coll])"]
  ["keep" "Lazy sequence of the non-nil results of (f item)." "([f] [f coll])"]
  ["keep-indexed" "Lazy sequence of the non-nil results of (f index item)." "([f] [f coll])"]
  ["map-indexed" "Lazy sequence of (f index item) for each item." "([f] [f coll])"]
  ["take" "Lazy sequence of the first n items. (take n) is a transducer." "([n] [n coll])"]
  ["drop" "Lazy sequence of all but the first n items." "([n] [n coll])"]
  ["take-while" "Lazy items from the front while (pred item) is true." "([pred] [pred coll])"]
  ["drop-while" "Lazy items after the leading run where (pred item) is true." "([pred] [pred coll])"]
  ["take-nth" "Every nth item of coll, lazily." "([n] [n coll])"]
  ["take-last" "The last n items of coll (eager)." "([n coll])"]
  ["drop-last" "All but the last n items, lazily." "([coll] [n coll])"]
  ["first" "The first item of coll, or nil when empty." "([coll])"]
  ["second" "Same as (first (next coll))." "([coll])"]
  ["rest" "The items after the first; () when none. Never nil." "([coll])"]
  ["next" "The items after the first, or nil when none remain." "([coll])"]
  ["last" "The final item of coll (walks the whole seq)." "([coll])"]
  ["butlast" "Everything but the final item (eager)." "([coll])"]
  ["nth" "The item at index n. Throws when out of bounds unless a not-found is given." "([coll index] [coll index not-found])"]
  ["cons" "A seq whose first is x and whose rest is coll." "([x seq])"]
  ["conj" "Adds item(s) to a collection at its natural insertion point: vectors append, lists prepend, sets/maps add." "([coll] [coll x] [coll x & xs])"]
  ["concat" "Lazy concatenation of any number of collections." "([] [x] [x y] [x y & zs])"]
  ["into" "Adds every item of `from` onto `to` (conj semantics); (into to xform from) applies a transducer." "([to from] [to xform from])"]
  ["seq" "A seq view of the collection, or nil when it is empty. The idiomatic emptiness test." "([coll])"]
  ["empty?" "True when coll has no items — same as (not (seq coll))." "([coll])"]
  ["count" "The number of items in the collection (O(1) for counted colls)." "([coll])"]
  ["range" "(range), (range end), (range start end step): lazy seq of numbers. No args = infinite." "([] [end] [start end] [start end step])"]
  ["repeat" "(repeat x) infinite xs; (repeat n x) n of them. Lazy." "([x] [n x])"]
  ["repeatedly" "Lazy sequence of calls to a zero-arg (side-effecting) fn." "([f] [n f])"]
  ["iterate" "Lazy infinite seq of x, (f x), (f (f x)), ..." "([f x])"]
  ["cycle" "Lazy infinite repetition of the items of coll." "([coll])"]
  ["interleave" "First items of each coll, then second items, etc., stopping at the shortest." "([] [c1] [c1 c2] [c1 c2 & colls])"]
  ["interpose" "The items of coll separated by sep, lazily." "([sep] [sep coll])"]
  ["partition" "Lazy blocks of n items (optionally stepped/padded); incomplete tail block is dropped unless padded." "([n coll] [n step coll] [n step pad coll])"]
  ["partition-all" "Like partition but keeps the incomplete final block." "([n] [n coll] [n step coll])"]
  ["partition-by" "Splits coll each time (f item) changes value, lazily." "([f] [f coll])"]
  ["split-at" "[(take n coll) (drop n coll)]" "([n coll])"]
  ["split-with" "[(take-while pred coll) (drop-while pred coll)]" "([pred coll])"]
  ["distinct" "Lazy sequence with duplicates removed." "([] [coll])"]
  ["dedupe" "Lazy sequence with consecutive duplicates collapsed." "([] [coll])"]
  ["flatten" "All nested sequential items as one flat lazy sequence." "([coll])"]
  ["reverse" "The items in reverse order (eager)." "([coll])"]
  ["sort" "Sorted seq of coll; (sort comp coll) with a comparator." "([coll] [comp coll])"]
  ["sort-by" "Sorts by (keyfn item), optionally with a comparator." "([keyfn coll] [keyfn comp coll])"]
  ["shuffle" "A random permutation of coll (note: cljc's is currently identity)." "([coll])"]
  ["frequencies" "Map from distinct item to number of occurrences." "([coll])"]
  ["group-by" "Map from (f item) to vector of items with that key." "([f coll])"]
  ["doall" "Forces a lazy sequence completely; returns it. Use for side effects held in a lazy seq." "([coll] [n coll])"]
  ["dorun" "Forces a lazy sequence for side effects; returns nil." "([coll] [n coll])"]
  ["lazy-seq" "Wraps body so it is evaluated only when the seq is consumed, once." "([& body])"]
  ["realized?" "Whether a delay/lazy value has been forced (cljc: coarse)."]
  ["some" "The first logical-true value of (pred item), else nil." "([pred coll])"]
  ["every?" "True if (pred item) is true for every item." "([pred coll])"]
  ["not-every?" "Complement of every?." "([pred coll])"]
  ["not-any?" "True when no item satisfies pred." "([pred coll])"]
  ["zipmap" "A map with keys mapped to vals, stopping at the shorter." "([keys vals])"]
  ["line-seq" "Lazy seq of lines from a reader."]
  ["tree-seq" "Lazy depth-first walk: branch? decides descent, children expands." "([branch? children root])"]
  ;; ── collections ──
  ["get" "The value at key (or index), or not-found/nil. Works on maps, vectors, sets, strings." "([map key] [map key not-found])"]
  ["get-in" "The value at a nested key path, e.g. (get-in m [:a :b])." "([m ks] [m ks not-found])"]
  ["assoc" "Map with key(s) mapped to val(s); on vectors, sets the index (append at count)." "([map key val] [map key val & kvs])"]
  ["assoc-in" "Sets a value at a nested key path, creating maps along the way." "([m ks v])"]
  ["update" "Map with the value at k replaced by (f old & args)." "([m k f] [m k f x] [m k f x y] [m k f x y & more])"]
  ["update-in" "Like update at a nested key path." "([m ks f & args])"]
  ["dissoc" "Map without the given key(s)." "([map] [map key] [map key & ks])"]
  ["disj" "Set without the given element(s)." "([set] [set k] [set k & ks])"]
  ["merge" "Later maps' entries win: (merge {:a 1} {:a 2 :b 3}) => {:a 2 :b 3}." "([& maps])"]
  ["merge-with" "Like merge, resolving key conflicts with (f left right)." "([f & maps])"]
  ["select-keys" "Map with only the entries whose keys are in keyseq." "([map keyseq])"]
  ["keys" "Sequence of the map's keys." "([map])"]
  ["vals" "Sequence of the map's values." "([map])"]
  ["contains?" "Whether the key (or index) is present — NOT a value search; use `some` for that." "([coll key])"]
  ["find" "The map entry [k v] for key, or nil." "([map key])"]
  ["peek" "Vectors: last item. Lists/queues: first. Maps (cljc): the min-priority entry." "([coll])"]
  ["pop" "The collection without its peek item." "([coll])"]
  ["subvec" "A vector view of v from start (to end), O(1)." "([v start] [v start end])"]
  ["vec" "An eager vector of the items of coll." "([coll])"]
  ["vector" "A vector of the arguments." "([& items])"]
  ["set" "A set of the items of coll." "([coll])"]
  ["hash-map" "A map from interleaved key/value arguments." "([& keyvals])"]
  ["hash-set" "A set of the arguments." "([& keys])"]
  ["sorted-map" "A map sorted by its keys (compare, or sorted-map-by comparator)." "([& keyvals])"]
  ["sorted-set" "A set sorted by compare (or sorted-set-by comparator)." "([& keys])"]
  ["subseq" "Entries of a sorted collection in a key range, e.g. (subseq sm >= 5)."]
  ["rsubseq" "Like subseq, descending."]
  ["transient" "A mutable-in-place edition of a vector/map/set for batch building; finish with persistent!." "([coll])"]
  ["persistent!" "Seals a transient back into an immutable collection." "([coll])"]
  ["conj!" "conj onto a transient." "([coll x])"]
  ["assoc!" "assoc onto a transient (or set an int-array slot in cljc)." "([coll key val])"]
  ["int-array" "(int-array n), (int-array n init), (int-array coll): a flat mutable int64 array (cljc native). Use aget/aset/alength." "([size] [size init-or-seq])"]
  ["aget" "Reads array slot i, O(1)." "([array idx])"]
  ["aset" "Writes array slot i, returning the value." "([array idx val])"]
  ["alength" "The array's length." "([array])"]
  ["empty" "An empty collection of the same category as coll." "([coll])"]
  ;; ── functions & control ──
  ["apply" "Calls f with the items of the final argument spliced in as arguments." "([f args] [f x args] [f x y args] [f x y z & args])"]
  ["partial" "A fn with some leading arguments preapplied." "([f] [f arg1] [f arg1 arg2] [f arg1 arg2 arg3 & more])"]
  ["comp" "Right-to-left function composition: ((comp f g) x) is (f (g x))." "([] [f] [f g] [f g & fs])"]
  ["juxt" "((juxt f g) x) => [(f x) (g x)]." "([f] [f g] [f g h] [f g h & fs])"]
  ["identity" "Returns its argument." "([x])"]
  ["constantly" "A fn that ignores its arguments and always returns x." "([x])"]
  ["fnil" "A fn that substitutes defaults for leading nil arguments before calling f." "([f x] [f x y] [f x y z])"]
  ["complement" "A fn returning the logical negation of f's result." "([f])"]
  ["every-pred" "A pred that is true when ALL given preds are true."]
  ["some-fn" "A fn returning the first logical-true result among the given fns."]
  ["memoize" "Caches f's results by argument list."]
  ["trampoline" "Calls f; while the result is a fn, calls it — flat mutual recursion."]
  ["if-let" "Binds then branches: (if-let [x expr] then else) — then runs with x bound when expr is truthy."]
  ["when-let" "(when-let [x expr] body...) — body runs with x bound when expr is truthy."]
  ["if-some" "Like if-let but tests (some? expr), so false is a hit."]
  ["when-some" "Like when-let but tests (some? expr)."]
  ["cond" "Pairs of test/expr: value of the expr after the first truthy test."]
  ["condp" "(condp pred expr & clauses): matches expr against clause keys with pred."]
  ["case" "Constant-time dispatch on identical(ish) constants; throws without a default."]
  ["cond->" "Threads x through the exprs whose paired tests are truthy."]
  ["cond->>" "Like cond-> threading last."]
  ["as->" "Threads through forms binding each result to the given name."]
  ["some->" "Threads while values are non-nil; stops at the first nil."]
  ["some->>" "Like some-> threading last."]
  ["doto" "Evaluates x, threads it as first arg through the forms (for side effects), returns x."]
  ["dotimes" "(dotimes [i n] body): runs body n times with i bound 0..n-1."]
  ["doseq" "Iterates for side effects with for-style bindings (:let/:when/:while); returns nil."]
  ["for" "Lazy list comprehension with :let/:when/:while modifiers."]
  ["loop" "Establishes bindings that recur re-enters with new values."]
  ["recur" "Rebinds the enclosing loop/fn bindings and jumps back — constant-stack iteration."]
  ["while" "Runs body repeatedly while test is truthy."]
  ["run!" "(reduce (fn [_ x] (f x)) nil coll) — eager side effects, returns nil."]
  ;; ── numbers ──
  ["inc" "One greater." "([x])"]
  ["dec" "One less." "([x])"]
  ["quot" "Truncating integer division." "([num div])"]
  ["rem" "Remainder with the dividend's sign." "([num div])"]
  ["mod" "Modulus with the divisor's sign (always ≥0 for positive divisors)." "([num div])"]
  ["max" "The greatest argument." "([x] [x y] [x y & more])"]
  ["min" "The least argument." "([x] [x y] [x y & more])"]
  ["abs" "Absolute value." "([a])"]
  ["gcd" "Greatest common divisor (cljc extension)."]
  ["even?" "Whether n is even." "([n])"]
  ["odd?" "Whether n is odd." "([n])"]
  ["zero?" "Whether x is zero." "([num])"]
  ["pos?" "Whether x is positive." "([num])"]
  ["neg?" "Whether x is negative." "([num])"]
  ["parse-long" "The string as a long, or nil if it isn't one."]
  ["parse-double" "The string as a double, or nil."]
  ["rand" "Random double in [0,n) (default n=1)." "([] [n])"]
  ["rand-int" "Random integer in [0,n)." "([n])"]
  ["rand-nth" "A random item of coll." "([coll])"]
  ["compare" "-1/0/1 comparator over comparable values (numbers, strings, keywords, vectors...)." "([x y])"]
  ;; ── strings (flat str/ aliases) ──
  ["str" "Concatenates the string forms of the arguments; nil is \"\"." "([] [x] [x & ys])"]
  ["pr-str" "The readable (edn) printed form as a string." "([& xs])"]
  ["prn" "Prints readably followed by a newline." "([& xs])"]
  ["println" "Prints human-readably with spaces and a newline." "([& xs])"]
  ["print" "Prints human-readably without a newline." "([& xs])"]
  ["format" "printf-style formatting: %s %d %f %x etc." "([fmt & args])"]
  ["subs" "Substring from start (to end)." "([s start] [s start end])"]
  ["str/join" "Concatenates the collection's items, optionally separated: (str/join \", \" xs)." "([coll] [separator coll])"]
  ["str/split" "Splits on a regex: (str/split s #\",\" limit?)." "([s re] [s re limit])"]
  ["str/split-lines" "Splits on \\n (and \\r\\n)." "([s])"]
  ["str/replace" "Replaces all matches of a string or #\"regex\" (with $1.. group refs or a fn)." "([s match replacement])"]
  ["str/replace-first" "Like str/replace, first match only." "([s match replacement])"]
  ["str/trim" "Without leading/trailing whitespace." "([s])"]
  ["str/triml" "Without leading whitespace." "([s])"]
  ["str/trimr" "Without trailing whitespace." "([s])"]
  ["str/upper-case" "ALL CAPS." "([s])"]
  ["str/lower-case" "all lower." "([s])"]
  ["str/capitalize" "First char upper, rest lower." "([s])"]
  ["str/starts-with?" "Whether s begins with substr." "([s substr])"]
  ["str/ends-with?" "Whether s ends with substr." "([s substr])"]
  ["str/includes?" "Whether s contains substr." "([s substr])"]
  ["str/index-of" "First index of a substring/char, or nil." "([s value] [s value from-index])"]
  ["str/last-index-of" "Last index of a substring/char, or nil." "([s value] [s value from-index])"]
  ["str/blank?" "True for nil, empty, or all-whitespace strings." "([s])"]
  ["str/reverse" "The string reversed." "([s])"]
  ;; ── regex ──
  ["re-find" "First match of the pattern in s: the string, or [match groups...] when the pattern has groups." "([re s])"]
  ["re-matches" "Like re-find but the pattern must match the ENTIRE string." "([re s])"]
  ["re-seq" "Lazy sequence of successive matches." "([re s])"]
  ["re-pattern" "Compiles a string into a regex pattern." "([s])"]
  ["re-replace" "cljc: replace all matches, with $1..$9 group refs in the replacement."]
  ;; ── state ──
  ["atom" "A mutable reference; read with @, update with swap!/reset!." "([x])"]
  ["swap!" "Sets an atom to (f current args...); returns the new value." "([atom f] [atom f x] [atom f x y] [atom f x y & args])"]
  ["reset!" "Sets an atom's value directly; returns it." "([atom newval])"]
  ["swap-vals!" "Like swap! but returns [old new]."]
  ["reset-vals!" "Like reset! but returns [old new]."]
  ["compare-and-set!" "Sets the atom to new only if it currently holds old; returns success."]
  ["deref" "The current value of an atom/delay/promise/var — reader sugar @x." "([ref])"]
  ["delay" "Defers body until the first deref, then caches."]
  ["force" "Derefs a delay, passes other values through."]
  ;; ── predicates & misc ──
  ["nil?" "Whether x is nil." "([x])"]
  ["some?" "Whether x is NOT nil (false is some?)." "([x])"]
  ["true?" "Whether x is exactly true." "([x])"]
  ["false?" "Whether x is exactly false." "([x])"]
  ["not" "Logical negation." "([x])"]
  ["boolean" "Coerces to true/false by truthiness." "([x])"]
  ["string?" "Whether x is a string." "([x])"]
  ["keyword?" "Whether x is a keyword." "([x])"]
  ["symbol?" "Whether x is a symbol." "([x])"]
  ["number?" "Whether x is a number." "([x])"]
  ["int?" "Whether x is a fixed-precision integer." "([x])"]
  ["integer?" "Whether x is any integer."]
  ["double?" "Whether x is a double."]
  ["fn?" "Whether x is a function." "([x])"]
  ["coll?" "Whether x is a collection." "([x])"]
  ["seq?" "Whether x is a seq (list-like)." "([x])"]
  ["sequential?" "Whether x is sequential (lists, vectors, seqs)." "([coll])"]
  ["associative?" "Whether x supports key lookup (maps, vectors)." "([coll])"]
  ["vector?" "Whether x is a vector." "([x])"]
  ["map?" "Whether x is a map." "([x])"]
  ["set?" "Whether x is a set." "([x])"]
  ["list?" "Whether x is a list." "([x])"]
  ["sorted?" "Whether x is a sorted collection."]
  ["keyword" "Makes a keyword from a name (and optional namespace): (keyword \"a\" \"b\") => :a/b." "([name] [ns name])"]
  ["symbol" "Makes a symbol from a name (and optional namespace)." "([name] [ns name])"]
  ["name" "The name part of a keyword/symbol/string." "([x])"]
  ["namespace" "The namespace part of a qualified keyword/symbol, or nil." "([x])"]
  ["gensym" "A unique symbol, optionally with a prefix." "([] [prefix-string])"]
  ["type" "The value's type (cljc: a keyword like :vector, :string)." "([x])"]
  ["instance?" "Whether x is of the given type/protocol." "([c x])"]
  ["identical?" "Pointer equality — same object."]
  ["hash" "The value's hash code (consistent with =)."]
  ["meta" "The metadata map of obj, or nil." "([obj])"]
  ["with-meta" "obj with the given metadata map attached." "([obj m])"]
  ["vary-meta" "obj with (apply f (meta obj) args) as metadata." "([obj f & args])"]
  ["slurp" "The entire contents of a file/stream as a string." "([f])"]
  ["spit" "Writes content to a file (stringified)." "([f content])"]
  ["read-string" "Reads one edn/Clojure form from the string." "([s])"]
  ["eval" "Evaluates a form (data) and returns the result." "([form])"]
  ["macroexpand-1" "One step of macro expansion for the form."]
  ["macroexpand" "Repeated macroexpand-1 until the head is no longer a macro."]
  ["time" "Evaluates body, prints elapsed time, returns the value."]
  ["assert" "Throws when x is falsy (with optional message)."]
  ["ex-info" "An exception carrying a message and a data map (and optional cause)."]
  ["ex-message" "The message of an exception."]
  ["ex-data" "The data map of an ex-info exception, else nil."]
  ["ex-cause" "The cause of an exception, or nil."]
  ["with-out-str" "Evaluates body capturing everything printed, returning it as a string."]
  ["doc" "Prints documentation for the named binding: (doc map)."]
  ["source" "Prints the (re-read) source of a fn defined from Clojure code: (source my-fn)."]
  ["apropos" "All defined names containing the string: (apropos \"index\")."]
  ["find-doc" "Prints docs for every binding whose name or docstring matches."]
  ;; ── multimethods & protocols ──
  ["defmulti" "Defines a multimethod dispatching on (dispatch-fn args...)."]
  ["defmethod" "Adds a method implementation for a dispatch value."]
  ["defprotocol" "Declares a named set of methods dispatched on the first argument's type."]
  ["defrecord" "Defines a named map-like type with fixed fields and protocol support."]
  ["deftype" "Defines a named type with fields (cljc: represented as a tagged map)."]
  ["derive" "Adds a parent relationship in the (global) hierarchy."]
  ["isa?" "Hierarchy-aware type/tag relation (vectors compare element-wise)."]
  ;; ── batteries (fs.clj / http.clj / json.clj / process.clj) ──
  ["fs/exists?" "Whether the path exists."]
  ["fs/directory?" "Whether the path is a directory."]
  ["fs/regular-file?" "Whether the path is a regular file."]
  ["fs/list-dir" "Sequence of entries in a directory."]
  ["fs/create-dir" "Creates the directory (and parents); true on success."]
  ["fs/delete" "Deletes a file or (empty) directory; true on success."]
  ["fs/move" "Renames/moves src to dst; true on success."]
  ["fs/copy" "Copies src to dst."]
  ["fs/file-name" "The final path segment."]
  ["fs/parent" "The parent directory of the path, or nil."]
  ["fs/extension" "The file extension without the dot, or nil."]
  ["fs/temp-dir" "The system temp directory."]
  ["fs/cwd" "The current working directory."]
  ["http/serve" "Starts the HTTP server on the csp event loop; returns the listening socket (drive with (csp/run!)). Handler gets a request map, returns a string or {:status :headers :body}."]
  ["http/run-server" "Starts the HTTP server and blocks, driving the csp event loop."]
  ["http/router" "Builds a handler from route entries [[method path-pattern handler] ...]."]
  ["http/request" "Performs an HTTP request from {:method :url :headers :body}; returns a channel of the response map."]
  ["http/get" "HTTP GET of a url; returns a channel of the response map."]
  ["http/post" "HTTP POST of a body to a url; returns a channel of the response map."]
  ["json/parse" "Parses a JSON string to Clojure data ((json/parse s) or (json/parse s {:keywords? true}))."]
  ["json/write" "Renders Clojure data as a JSON string."]
  ["process/sh" "Runs a shell command, returns {:exit :out} (stderr folded into :out)."]
  ["process/shell" "Like process/sh but throws ex-info on nonzero exit."]
  ["process/out" "The trimmed stdout of running the command."]
  ["process/escape" "Shell-escapes a string for safe interpolation."]])

;; ── special forms & core macros (not bindings — served straight from the
;;    registry; the third slot holds a usage form instead of fn arglists) ──
(run! (fn [[n d a]] (cljc/doc-put* n d a))
 [["if" "Special form. Evaluates test; if truthy (anything but nil/false), evaluates and returns then, otherwise else (or nil)." "((if test then else?))"]
  ["do" "Special form. Evaluates the exprs in order, returns the last (nil when empty)." "((do exprs*))"]
  ["let" "Special form. Binds names to values in order (later bindings see earlier ones); evaluates body with them in scope. Destructuring supported." "((let [bindings*] exprs*))"]
  ["fn" "Special form. An anonymous function; multiple arity clauses allowed, & gathers rest args. #(...) is shorthand with % %1 %2." "((fn name? [params*] exprs*) (fn name? ([params*] exprs*)+))"]
  ["def" "Special form. Interns a root binding for the symbol, optionally with a docstring and init value." "((def symbol doc-string? init?))"]
  ["loop" "Special form. Like let, but marks a recur target: (recur ...) rebinds the loop bindings and jumps back without consuming stack." "((loop [bindings*] exprs*))"]
  ["recur" "Special form. Rebinds the enclosing loop/fn bindings to the given values and jumps back — cljc's tail call. Must be in tail position." "((recur exprs*))"]
  ["quote" "Special form. Returns the form unevaluated. 'x reads as (quote x)." "((quote form))"]
  ["var" "Special form. Returns the Var named by the symbol (also #'sym). Its meta carries :name/:doc/:arglists." "((var symbol))"]
  ["throw" "Special form. Throws a value; catch it with try/catch. Use ex-info to build data-carrying exceptions." "((throw expr))"]
  ["try" "Special form. Evaluates body; on a throw, the first matching catch clause runs with the exception bound; finally always runs." "((try exprs* (catch Exception e exprs*)? (finally exprs*)?))"]
  ["when" "Macro. Evaluates body when test is truthy, else nil. No else branch — use if for that." "((when test exprs*))"]
  ["when-not" "Macro. Evaluates body when test is falsey." "((when-not test exprs*))"]
  ["when-let" "Macro. Binds the value of test; evaluates body when it is truthy." "((when-let [sym test] exprs*))"]
  ["when-some" "Macro. Like when-let but tests for non-nil rather than truthy." "((when-some [sym test] exprs*))"]
  ["if-let" "Macro. Binds the value of test; if truthy evaluates then with it bound, else else." "((if-let [sym test] then else?))"]
  ["if-some" "Macro. Like if-let but tests for non-nil (false counts as some)." "((if-some [sym test] then else?))"]
  ["if-not" "Macro. (if (not test) then else)." "((if-not test then else?))"]
  ["and" "Macro. Evaluates left to right, returns the first falsey value or the last value. () => true." "((and) (and x) (and x & next))"]
  ["or" "Macro. Evaluates left to right, returns the first truthy value or the last value. () => nil." "((or) (or x) (or x & next))"]
  ["->" "Macro. Thread-first: inserts each result as the SECOND item of the next form. (-> x (f a) g) => (g (f x a))." "((-> x & forms))"]
  ["->>" "Macro. Thread-last: inserts each result as the LAST item of the next form. (->> x (f a) g) => (g (f a x))." "((->> x & forms))"]
  ["as->" "Macro. Threads x through forms with an explicit name for the previous result." "((as-> expr name & forms))"]
  ["some->" "Macro. Thread-first, but stops (returns nil) at the first nil result." "((some-> expr & forms))"]
  ["some->>" "Macro. Thread-last, short-circuiting on nil." "((some->> expr & forms))"]
  ["cond->" "Macro. Threads expr through the forms whose paired test is truthy (tests are NOT threaded)." "((cond-> expr & test-form-pairs))"]
  ["doto" "Macro. Evaluates x, calls each form with x inserted second (for side effects), returns x." "((doto x & forms))"]
  ["dotimes" "Macro. Runs body n times with the name bound to 0..n-1; returns nil." "((dotimes [name n] exprs*))"]
  ["doseq" "Macro. Iterates the seq(s) for side effects; supports :let :when :while like for. Returns nil." "((doseq [seq-exprs*] exprs*))"]
  ["for" "Macro. List comprehension: lazy seq of body evaluated across the bindings; modifiers :let :when :while." "((for [seq-exprs*] body-expr))"]
  ["defn" "Macro. (def name (fn ...)) with docstring and multi-arity support; registers the docstring for (doc name)." "((defn name doc-string? [params*] exprs*) (defn name doc-string? ([params*] exprs*)+))"]
  ["defn-" "Macro. Like defn but marks the var private to its namespace." "((defn- name doc-string? [params*] exprs*))"]
  ["defmacro" "Macro. Defines a macro: the fn receives unevaluated forms and returns a replacement form." "((defmacro name doc-string? [params*] exprs*))"]
  ["defonce" "Macro. defs the value only if the symbol has no root binding yet." "((defonce name expr))"]
  ["declare" "Macro. Forward-declares names so later defs can be referenced before definition." "((declare & names))"]
  ["binding" "Macro. Temporarily rebinds dynamic (root) vars for the extent of the body, restoring on exit." "((binding [var-val-pairs*] exprs*))"]
  ["letfn" "Macro. Binds locally-scoped, mutually recursive fns for the body." "((letfn [(name [params*] exprs*)+] exprs*))"]
  ["case" "Macro. Constant-time dispatch on compile-time literal test values; last arg is the default, throws when absent and unmatched." "((case e & test-result-pairs default?))"]
  ["condp" "Macro. (condp pred expr ...) — first clause where (pred test-val expr) is truthy." "((condp pred expr & clauses))"]
  ["ns" "Macro. Names the current namespace and processes :require/:refer/:as clauses." "((ns name & clauses))"]
  ["require" "Loads namespaces from *load-path* (name → path: . becomes /, - becomes _). Supports [ns :as alias] and [ns :refer [syms]]." "((require & specs))"]
  ["comment" "Macro. Ignores its body, returns nil." "((comment & body))"]
  ["time" "Macro. Evaluates expr, prints elapsed milliseconds, returns the value." "((time expr))"]
  ["with-out-str" "Macro. Evaluates body capturing *out*; returns what it printed as a string." "((with-out-str & body))"]
  ["delay" "Macro. Wraps body in an unrealized Delay: deref/force evaluates once and caches." "((delay & body))"]
  ["lazy-seq" "Macro. Wraps body in an unrealized lazy sequence; realized once on first seq access." "((lazy-seq & body))"]])
